/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSettingsRouteImport } from './routes/user-settings'
import { Route as SignupCheckEmailRouteImport } from './routes/signup-check-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginVerificationRouteImport } from './routes/login-verification'
import { Route as LoginPasskeyRouteImport } from './routes/login-passkey'
import { Route as LoginCheckEmailRouteImport } from './routes/login-check-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSignupTokenRouteImport } from './routes/signup.$signupToken'
import { Route as LoginViaLinkLoginLinkTokenRouteImport } from './routes/login-via-link.$loginLinkToken'

const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCheckEmailRoute = SignupCheckEmailRouteImport.update({
  id: '/signup-check-email',
  path: '/signup-check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerificationRoute = LoginVerificationRouteImport.update({
  id: '/login-verification',
  path: '/login-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasskeyRoute = LoginPasskeyRouteImport.update({
  id: '/login-passkey',
  path: '/login-passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckEmailRoute = LoginCheckEmailRouteImport.update({
  id: '/login-check-email',
  path: '/login-check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSignupTokenRoute = SignupSignupTokenRouteImport.update({
  id: '/$signupToken',
  path: '/$signupToken',
  getParentRoute: () => SignupRoute,
} as any)
const LoginViaLinkLoginLinkTokenRoute =
  LoginViaLinkLoginLinkTokenRouteImport.update({
    id: '/login-via-link/$loginLinkToken',
    path: '/login-via-link/$loginLinkToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-check-email': typeof LoginCheckEmailRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-verification': typeof LoginVerificationRoute
  '/signup': typeof SignupRouteWithChildren
  '/signup-check-email': typeof SignupCheckEmailRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-link/$loginLinkToken': typeof LoginViaLinkLoginLinkTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-check-email': typeof LoginCheckEmailRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-verification': typeof LoginVerificationRoute
  '/signup': typeof SignupRouteWithChildren
  '/signup-check-email': typeof SignupCheckEmailRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-link/$loginLinkToken': typeof LoginViaLinkLoginLinkTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-check-email': typeof LoginCheckEmailRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-verification': typeof LoginVerificationRoute
  '/signup': typeof SignupRouteWithChildren
  '/signup-check-email': typeof SignupCheckEmailRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-link/$loginLinkToken': typeof LoginViaLinkLoginLinkTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-check-email'
    | '/login-passkey'
    | '/login-verification'
    | '/signup'
    | '/signup-check-email'
    | '/user-settings'
    | '/login-via-link/$loginLinkToken'
    | '/signup/$signupToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-check-email'
    | '/login-passkey'
    | '/login-verification'
    | '/signup'
    | '/signup-check-email'
    | '/user-settings'
    | '/login-via-link/$loginLinkToken'
    | '/signup/$signupToken'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/login-check-email'
    | '/login-passkey'
    | '/login-verification'
    | '/signup'
    | '/signup-check-email'
    | '/user-settings'
    | '/login-via-link/$loginLinkToken'
    | '/signup/$signupToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LoginCheckEmailRoute: typeof LoginCheckEmailRoute
  LoginPasskeyRoute: typeof LoginPasskeyRoute
  LoginVerificationRoute: typeof LoginVerificationRoute
  SignupRoute: typeof SignupRouteWithChildren
  SignupCheckEmailRoute: typeof SignupCheckEmailRoute
  UserSettingsRoute: typeof UserSettingsRoute
  LoginViaLinkLoginLinkTokenRoute: typeof LoginViaLinkLoginLinkTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-check-email': {
      id: '/signup-check-email'
      path: '/signup-check-email'
      fullPath: '/signup-check-email'
      preLoaderRoute: typeof SignupCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-verification': {
      id: '/login-verification'
      path: '/login-verification'
      fullPath: '/login-verification'
      preLoaderRoute: typeof LoginVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-passkey': {
      id: '/login-passkey'
      path: '/login-passkey'
      fullPath: '/login-passkey'
      preLoaderRoute: typeof LoginPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-check-email': {
      id: '/login-check-email'
      path: '/login-check-email'
      fullPath: '/login-check-email'
      preLoaderRoute: typeof LoginCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$signupToken': {
      id: '/signup/$signupToken'
      path: '/$signupToken'
      fullPath: '/signup/$signupToken'
      preLoaderRoute: typeof SignupSignupTokenRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login-via-link/$loginLinkToken': {
      id: '/login-via-link/$loginLinkToken'
      path: '/login-via-link/$loginLinkToken'
      fullPath: '/login-via-link/$loginLinkToken'
      preLoaderRoute: typeof LoginViaLinkLoginLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupSignupTokenRoute: typeof SignupSignupTokenRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSignupTokenRoute: SignupSignupTokenRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LoginCheckEmailRoute: LoginCheckEmailRoute,
  LoginPasskeyRoute: LoginPasskeyRoute,
  LoginVerificationRoute: LoginVerificationRoute,
  SignupRoute: SignupRouteWithChildren,
  SignupCheckEmailRoute: SignupCheckEmailRoute,
  UserSettingsRoute: UserSettingsRoute,
  LoginViaLinkLoginLinkTokenRoute: LoginViaLinkLoginLinkTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
